CREATE TABLE IF NOT EXISTS users(
username VARCHAR(32) NOT NULL PRIMARY KEY,
pass VARCHAR(200) NOT NULL
)
ENGINE INNODB
CHARSET UTF8;

CREATE TABLE IF NOT EXISTS recipe(
id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
title VARCHAR(75) NOT NULL,
image VARCHAR(256),
ingrediens VARCHAR(250) NOT NULL,
descriptions VARCHAR(150) NOT NULL,
guide VARCHAR(300) NOT NULL,
category VARCHAR(40) NOT NULL,
username VARCHAR(32) NOT NULL
/*,FOREIGN KEY (username) REFERENCES users(username)*/
)
ENGINE INNODB
CHARSET UTF8;

CREATE TABLE IF NOT EXISTS comments(
id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
user_id VARCHAR(32) NOT NULL,
recipe_id INT NOT NULL,
comment VARCHAR(128),
FOREIGN KEY (user_id) REFERENCES users(username),
FOREIGN KEY (recipe_id) REFERENCES recipe(id)
)
ENGINE INNODB
CHARSET UTF8;

CREATE TABLE IF NOT EXISTS likes(
id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
recipe_like INT NOT NULL,
FOREIGN KEY (recipe_like) REFERENCES recipe(id)
)
ENGINE INNODB
CHARSET UTF8;